// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface SolidityPackTypes$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "SolidityPackTypes";
  readonly sourceName: "contracts/SolidityPackTypes.sol";
  readonly abi: [];
  readonly bytecode: "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220f11aefe09d10ffbd7a691ade68e04e4f54fe94bab03a9ea1ff713e560d4d1d8864736f6c63430008140033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220f11aefe09d10ffbd7a691ade68e04e4f54fe94bab03a9ea1ff713e560d4d1d8864736f6c63430008140033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/SolidityPackTypes.sol";
  readonly buildInfoId: "solc-0_8_20-49af8afb3f2bbf849e4c9db17637e2fb8e232bc2";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["SolidityPackTypes"]: SolidityPackTypes$Type;
    ["contracts/SolidityPackTypes.sol:SolidityPackTypes"]: SolidityPackTypes$Type;
  }
}