// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface SolidityPackDecoder$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "SolidityPackDecoder";
  readonly sourceName: "contracts/SolidityPackDecoder.sol";
  readonly abi: [];
  readonly bytecode: "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212207c7a68c5ba5a82abeb4dd701f96505735a766698b8a94c4ce7c628e4f4546ed264736f6c63430008140033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f80fdfea26469706673582212207c7a68c5ba5a82abeb4dd701f96505735a766698b8a94c4ce7c628e4f4546ed264736f6c63430008140033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/SolidityPackDecoder.sol";
  readonly buildInfoId: "solc-0_8_20-291b827980c63e54964ffedf78e56246a606e21f";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["SolidityPackDecoder"]: SolidityPackDecoder$Type;
    ["contracts/SolidityPackDecoder.sol:SolidityPackDecoder"]: SolidityPackDecoder$Type;
  }
}